version: '24.0.5'

###network
networks:
  lms-network:
    driver: bridge

###volume
volumes:
  lms-source-vol:
    driver: local
    driver_opts:
      device: ./disk/moodle-node/source/sites
      type: none
      o: bind
  ##volume caching redis
  lms-redis:
    driver: local
    driver_opts:
      device: ./disk/caching-redis/data
      type: none
      o: bind
  ##volume storage minio
  lms-minio:
    driver: local
    driver_opts:
      device: ./disk/storage-minio/data
      type: none
      o: bind
  ##volume db cluster galena
  #volume db node 1 / master
  lms-db-node1:
    driver: local
    driver_opts:
      device: ./disk/maria-db/data/node1
      type: none
      o: bind
  #volume db node 2
  lms-db-node2:
    driver: local
    driver_opts:
      device: ./disk/maria-db/data/node2
      type: none
      o: bind
  #volume db node 3
  lms-db-node3:
    driver: local
    driver_opts:
      device: ./disk/maria-db/data/node3
      type: none
      o: bind
  #volume nfs service
  lms-nfs-service-vol:
    driver: local
    driver_opts:
      device: ./disk/nfs-service/data
      type: none
      o: bind
  # #volume nfs service: dÃ¹ng cho lms node
  # lms-nfs-service-vol-driver:
  #   driver: local
  #   driver_opts:
  #     type: nfs
  #     o: addr=lms-nfs-service-cn,nolock,soft,rw
  #     device: ":/lms/data"

###services
services:
  ##container caching redis
  lms-caching:
    container_name: lms-caching-cn
    build: 
      dockerfile: Dockerfile
      context: ./disk/caching-redis/
    hostname: lms-caching-hn
    restart: always
    networks:
      - lms-network
    volumes:
      - ./disk/caching-redis/config/redis.conf:/etc/redis/redis.conf
      - lms-redis:/data
    ports:
      - "6379:6379"
    command: redis-server /etc/redis/redis.conf
  ##container storage minio
  lms-storage:
    container_name: lms-storage-cn
    image: "minio/minio:latest"
    hostname: lms-storage-hn
    restart: always
    networks:
      - lms-network
    volumes:
      - lms-minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=lmsAdminMinioStrageAcc
      - MINIO_ROOT_PASSWORD=lmsAdminMinioStragePass
      #- MINIO_BROWSER_REDIRECT_URL=https://console.example.vn
      #- MINIO_SERVER_URL=https://minio.example.vn
    command: server --console-address ":9001" /data
  ##container mariadb
  #slave node 1 / master
  lms-db-01:
    container_name: lms-db-01-cn
    hostname: lms-db-01-hn
    #image: docker.io/bitnami/mariadb-galera:10.7
    image: bitnami/mariadb-galera:latest
    ports:
      - '3391:3306'
      #- '4444:4444'
      #- '4567:4567'
      #- '4568:4568'
    networks:
      - lms-network
    volumes:
      - ./disk/maria-db/config/node1/my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:ro
      - lms-db-node1:/bitnami/mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_GALERA_CLUSTER_NAME=mariadb-cluster
      - MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes
      - MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP=yes
      # MARIADB_GALERA_CLUSTER_ADDRESS point to bootstrap node
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://lms-db-01:4567,lms-db-02:4567,lms-db-03:4567,0.0.0.0:4567
      - MARIADB_EXTRA_FLAGS=--max-connect-errors=1000 --max_connections=155
      - MARIADB_GALERA_MARIABACKUP_USER=mariadb_backup_user
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=backup_pwd
      - MARIADB_ROOT_PASSWORD=root_password
      - MARIADB_REPLICATION_USER=rep_user
      - MARIADB_REPLICATION_PASSWORD=rep_pwd
      - MARIADB_DATABASE=moodle_eduvtclms
    #command: mariadb -u root -proot_password moodle_eduvtclms > /bitnami/mariadb/moodle_eduvtclms.sql
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
  #slave node 2
  lms-db-02:
    container_name: lms-db-02-cn
    hostname: lms-db-02-hn
    #image: docker.io/bitnami/mariadb-galera:10.7
    image: bitnami/mariadb-galera:latest
    ports:
      - '3392:3306'
      #- '4444:4444'
      #- '4567:4567'
      #- '4568:4568'
    networks:
      - lms-network
    volumes:
      - ./disk/maria-db/config/node2/my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:ro
      - lms-db-node2:/bitnami/mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_GALERA_CLUSTER_NAME=mariadb-cluster
      #- MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes
      #- MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP=yes
      # MARIADB_GALERA_CLUSTER_ADDRESS point to bootstrap node
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://lms-db-01:4567,lms-db-02:4567,lms-db-03:4567,0.0.0.0:4567
      - MARIADB_EXTRA_FLAGS=--max-connect-errors=1000 --max_connections=155
      - MARIADB_GALERA_MARIABACKUP_USER=mariadb_backup_user
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=backup_pwd
      - MARIADB_ROOT_PASSWORD=root_password
      - MARIADB_REPLICATION_USER=rep_user
      - MARIADB_REPLICATION_PASSWORD=rep_pwd
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
  #slave node 3
  lms-db-03:
    container_name: lms-db-03-cn
    hostname: lms-db-03-hn
    #image: docker.io/bitnami/mariadb-galera:10.7
    image: bitnami/mariadb-galera:latest
    ports:
      - '3393:3306'
      #- '4444:4444'
      #- '4567:4567'
      #- '4568:4568'
    networks:
      - lms-network
    volumes:
      - ./disk/maria-db/config/node3/my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:ro
      - lms-db-node3:/bitnami/mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_GALERA_CLUSTER_NAME=mariadb-cluster
        # MARIADB_GALERA_CLUSTER_ADDRESS point to bootstrap node
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://lms-db-01:4567,lms-db-02:4567,lms-db-03:4567,0.0.0.0:4567
      - MARIADB_EXTRA_FLAGS=--max-connect-errors=1000 --max_connections=155
      - MARIADB_GALERA_MARIABACKUP_USER=mariadb_backup_user
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=backup_pwd
      - MARIADB_ROOT_PASSWORD=root_password
      - MARIADB_REPLICATION_USER=rep_user
      - MARIADB_REPLICATION_PASSWORD=rep_pwd
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
  #phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - 8081:80
    environment:
      - UPLOAD_LIMIT=1G
      - MEMORY_LIMIT=2G
      - PMA_HOST=lms-db-01-cn:3306
    container_name: myphpadmin
    depends_on:
      - lms-db-01
    networks:
      - lms-network
  
  ##container lms node
  #lms node 1 : nginx + php + lms moodle code
  lms-node1-nginx:
    image: nginx:stable-alpine3.17
    privileged: true
    container_name: lms-node1-nginx-cn
    hostname: lms-node1-nginx-hn
    restart: unless-stopped
    # depends_on:
    #   - lms-nfs-service
    networks:
      - lms-network
    volumes:
      - ./disk/moodle-node/nginx/config/node1/default.conf:/etc/nginx/conf.d/default.conf
      - ./disk/moodle-node/nginx/config/node1/nginx.conf:/etc/nginx/nginx.conf
      - lms-source-vol:/home/www/html/   
    #  - lms-nfs-service-vol-driver:/lms/data
      - lms-nfs-service-vol:/lms/data
    ports:
        - 80:80 

  lms-node1-phpfpm:
    build: 
      dockerfile: Dockerfile
      context: ./disk/moodle-node/php-fpm/
    privileged: true
    container_name: lms-node1-phpfpm-cn
    hostname: lms-node1-phpfpm-hn
    restart: unless-stopped
    depends_on:
      - lms-nfs-service
    networks:
      - lms-network
    volumes:
      - ./disk/moodle-node/php-fpm/config/node1/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./disk/moodle-node/php-fpm/config/node1/php.ini:/usr/local/etc/php/php.ini
      - lms-source-vol:/home/www/html/
      #- lms-nfs-service-vol-driver:/lms/data
      - lms-nfs-service-vol:/lms/data
    
  #lms node 2 : nginx + php + lms moodle code
  
  #lms node 3 : nginx + php + lms moodle code
   
  ##container lb 
  # lms-lb-nginx:
  #   image: nginx:stable-alpine3.17
  #   container_name: lms-lb-nginx-cn
  #   hostname: lms-lb-nginx-hn
  #   restart: always
  #   networks:
  #     - lms-network
  #   volumes:
  #     - ./disk/lb-nginx/config/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./disk/lb-nginx/config/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - 80:80     
  #     - 443:443     
  ##container nfs service
  lms-nfs-service:
    labels:
      io.rancher.container.dns: 'true'
    image: itsthenetwork/nfs-server-alpine:12
    container_name: lms-nfs-service-cn
    hostname: lms-nfs-service-hn
    restart: always
    privileged: true
    networks:
      - lms-network
    environment:
      - SHARED_DIRECTORY=/lms/data
    volumes:
      - lms-nfs-service-vol:/lms/data

